# Generated by Django 4.0 on 2025-10-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название аудитории')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassTimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип расписания',
                'verbose_name_plural': 'Типы расписаний',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название дисциплины')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Код дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО преподавателя')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('pair_number', models.IntegerField(verbose_name='Номер пары')),
                ('subgroup', models.CharField(blank=True, max_length=50, verbose_name='Подгруппа')),
                ('lesson_type', models.CharField(blank=True, max_length=20, verbose_name='Тип занятия (Л/пр/лаб)')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн занятие')),
                ('platform', models.CharField(blank=True, max_length=100, verbose_name='Платформа (Moodle и т.д.)')),
                ('class_time_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classtimetype', verbose_name='Тип расписания')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classroom', verbose_name='Аудитория')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.discipline', verbose_name='Дисциплина')),
                ('groups', models.ManyToManyField(to='schedule.StudentGroup', verbose_name='Группы')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ['date', 'pair_number'],
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_number', models.IntegerField(verbose_name='Номер пары')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('class_time_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classtimetype', verbose_name='Тип расписания')),
            ],
            options={
                'verbose_name': 'Время пары',
                'verbose_name_plural': 'Время пар',
                'ordering': ['class_time_type', 'pair_number'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['date'], name='schedule_sc_date_442eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher'], name='schedule_sc_teacher_5415b8_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['pair_number'], name='schedule_sc_pair_nu_9d8e50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classtime',
            unique_together={('class_time_type', 'pair_number')},
        ),
    ]
