# Generated by Django 4.0 on 2025-10-19 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='schedule',
            name='schedule_sc_pair_nu_9d8e50_idx',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pair_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.classtime', verbose_name='Номер пары'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['pair_number'], name='schedule_sc_pair_nu_3bfc29_idx'),
        ),
    ]
