# Generated by Django 4.0 on 2025-10-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='name_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фио'),
        ),
    ]
