# Generated by Django 4.0 on 2025-10-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_telegramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulepublication',
            options={'verbose_name': 'Публикация расписания', 'verbose_name_plural': 'Публикация расписаний'},
        ),
        migrations.AlterField(
            model_name='schedulepublication',
            name='excel_file',
            field=models.FileField(upload_to='schedule_excels/'),
        ),
    ]
