# Generated by Django 4.0 on 2025-10-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_schedulepublication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='Дата расписания')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Уведомление отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('recipients_count', models.IntegerField(default=0, verbose_name='Кол-во получателей')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
            },
        ),
    ]
